/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.gsitranslate.gui;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import org.gsitranslate.translationapp.PropertiesUtil;

/**
 *
 * @author samuelvarejao
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        addEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        result_list = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        FBV_textfield = new javax.swing.JTextField();
        FBV_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FBV_langs = new javax.swing.JPanel();
        FBV_lang_pt = new javax.swing.JCheckBox();
        FBV_lang_en = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        FBK_button = new javax.swing.JButton();
        FBK_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        D_textfield = new javax.swing.JTextField();
        D_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        U_textfield2 = new javax.swing.JTextField();
        U_button = new javax.swing.JButton();
        U_langs = new javax.swing.JPanel();
        U_lang_pt = new javax.swing.JCheckBox();
        U_lang_en = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        U_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        S_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LANG_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PT_textField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EN_textField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ES_textField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        IT_textField = new javax.swing.JTextField();
        LANG_LOAD_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        result_list.setBackground(new java.awt.Color(250, 250, 250));
        result_list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        result_list.setPreferredSize(new java.awt.Dimension(500, 500));
        result_list.setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout result_listLayout = new javax.swing.GroupLayout(result_list);
        result_list.setLayout(result_listLayout);
        result_listLayout.setHorizontalGroup(
            result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        result_listLayout.setVerticalGroup(
            result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(250, 250, 250));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jTabbedPane2.setBackground(new java.awt.Color(0, 157, 255));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 100));

        FBV_textfield.setBackground(new java.awt.Color(255, 255, 255));
        FBV_textfield.setForeground(new java.awt.Color(0, 0, 0));
        FBV_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        FBV_button.setBackground(new java.awt.Color(255, 255, 255));
        FBV_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        FBV_button.setForeground(new java.awt.Color(144, 144, 144));
        FBV_button.setText("Find");
        FBV_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBV_buttonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(144, 144, 144));
        jLabel2.setForeground(new java.awt.Color(144, 144, 144));
        jLabel2.setText("Find by value:");

        FBV_langs.setBackground(new java.awt.Color(255, 255, 255));
        FBV_langs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));

        FBV_lang_pt.setText("pt");

        FBV_lang_en.setText("en");

        javax.swing.GroupLayout FBV_langsLayout = new javax.swing.GroupLayout(FBV_langs);
        FBV_langs.setLayout(FBV_langsLayout);
        FBV_langsLayout.setHorizontalGroup(
            FBV_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FBV_langsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FBV_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FBV_lang_pt)
                    .addComponent(FBV_lang_en))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        FBV_langsLayout.setVerticalGroup(
            FBV_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FBV_langsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FBV_lang_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FBV_lang_en)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FBV_button)
                            .addComponent(FBV_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addComponent(FBV_langs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FBV_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FBV_langs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FBV_button)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("VALUE", jPanel2);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));

        FBK_button.setBackground(new java.awt.Color(255, 255, 255));
        FBK_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        FBK_button.setForeground(new java.awt.Color(144, 144, 144));
        FBK_button.setText("Find");
        FBK_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBK_buttonActionPerformed(evt);
            }
        });

        FBK_textfield.setBackground(new java.awt.Color(255, 255, 255));
        FBK_textfield.setForeground(new java.awt.Color(0, 0, 0));
        FBK_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        jLabel1.setBackground(new java.awt.Color(144, 144, 144));
        jLabel1.setForeground(new java.awt.Color(144, 144, 144));
        jLabel1.setText("Find by key:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FBK_button)
                            .addComponent(FBK_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FBK_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FBK_button)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("KEY", jPanel1);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel3.setBackground(new java.awt.Color(144, 144, 144));
        jLabel3.setForeground(new java.awt.Color(144, 144, 144));
        jLabel3.setText("Delete entry:");

        D_textfield.setBackground(new java.awt.Color(255, 255, 255));
        D_textfield.setForeground(new java.awt.Color(0, 0, 0));
        D_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        D_button.setBackground(new java.awt.Color(255, 255, 255));
        D_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        D_button.setForeground(new java.awt.Color(144, 144, 144));
        D_button.setText("Delete");
        D_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(D_button)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(D_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(D_button)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("DELETE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel4.setBackground(new java.awt.Color(144, 144, 144));
        jLabel4.setText("Add/ Update entry:");

        U_textfield2.setBackground(new java.awt.Color(255, 255, 255));
        U_textfield2.setForeground(new java.awt.Color(0, 0, 0));
        U_textfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        U_button.setBackground(new java.awt.Color(255, 255, 255));
        U_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        U_button.setForeground(new java.awt.Color(144, 144, 144));
        U_button.setText("Add/Update");
        U_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_buttonActionPerformed(evt);
            }
        });

        U_langs.setBackground(new java.awt.Color(255, 255, 255));
        U_langs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        U_lang_pt.setText("pt");

        U_lang_en.setText("en");

        javax.swing.GroupLayout U_langsLayout = new javax.swing.GroupLayout(U_langs);
        U_langs.setLayout(U_langsLayout);
        U_langsLayout.setHorizontalGroup(
            U_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(U_langsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(U_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(U_lang_pt)
                    .addComponent(U_lang_en))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        U_langsLayout.setVerticalGroup(
            U_langsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(U_langsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(U_lang_pt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U_lang_en)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Value:");

        U_textfield.setBackground(new java.awt.Color(255, 255, 255));
        U_textfield.setForeground(new java.awt.Color(0, 0, 0));
        U_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));

        jLabel6.setText("Key:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(U_button)
                                .addComponent(U_textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(U_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(U_langs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(U_langs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U_textfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(U_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ADD/ UPDATE", jPanel4);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        S_button.setBackground(new java.awt.Color(255, 255, 255));
        S_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        S_button.setForeground(new java.awt.Color(144, 144, 144));
        S_button.setText("Sort");
        S_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_buttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(144, 144, 144));
        jLabel7.setText("Util:");

        LANG_panel.setBackground(new java.awt.Color(250, 250, 250));
        LANG_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 225, 225)));
        LANG_panel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setText("PT");

        PT_textField.setBackground(new java.awt.Color(255, 255, 255));
        PT_textField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));
        PT_textField.setName("pt"); // NOI18N

        jLabel9.setText("EN");

        EN_textField.setBackground(new java.awt.Color(255, 255, 255));
        EN_textField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));
        EN_textField.setName("en"); // NOI18N

        jLabel10.setText("ES");

        ES_textField.setBackground(new java.awt.Color(255, 255, 255));
        ES_textField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));
        ES_textField.setName("es"); // NOI18N

        jLabel11.setText("IT");

        IT_textField.setBackground(new java.awt.Color(255, 255, 255));
        IT_textField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 225, 225), 1, true));
        IT_textField.setName("it"); // NOI18N

        LANG_LOAD_button.setBackground(new java.awt.Color(255, 255, 255));
        LANG_LOAD_button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LANG_LOAD_button.setForeground(new java.awt.Color(144, 144, 144));
        LANG_LOAD_button.setText("Load");
        LANG_LOAD_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LANG_LOAD_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LANG_panelLayout = new javax.swing.GroupLayout(LANG_panel);
        LANG_panel.setLayout(LANG_panelLayout);
        LANG_panelLayout.setHorizontalGroup(
            LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LANG_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LANG_panelLayout.createSequentialGroup()
                        .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IT_textField)
                            .addComponent(ES_textField)))
                    .addGroup(LANG_panelLayout.createSequentialGroup()
                        .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PT_textField)
                            .addComponent(EN_textField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LANG_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LANG_LOAD_button)))
                .addContainerGap())
        );
        LANG_panelLayout.setVerticalGroup(
            LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LANG_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PT_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(EN_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ES_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LANG_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(IT_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LANG_LOAD_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_list, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(S_button))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LANG_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result_list, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(S_button)
                .addGap(18, 18, 18)
                .addComponent(LANG_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    HashMap<String, String> languages = new HashMap();

    //DELETE
    private void D_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_buttonActionPerformed
        PropertiesUtil propertiesUtil = new PropertiesUtil();

        try {
            propertiesUtil.init(languages);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        String value = D_textfield.getText();
        try {
            propertiesUtil.delete(value);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_D_buttonActionPerformed

    //FIND BY VALUE
    private void FBV_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBV_buttonActionPerformed
        PropertiesUtil propertiesUtil = new PropertiesUtil();

        try {
            propertiesUtil.init(languages);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayList<String> value = new ArrayList();

        // Checks selected languages via selected checkboxes
        JPanel panel = FBV_langs;
        Component[] components = panel.getComponents();

        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    String lang = checkBox.getText();

                    try {
                        //Adds results from language to "value"
                        value.addAll(propertiesUtil.findKeysByValue(FBV_textfield.getText(), lang));

                    } catch (IOException ex) {
                        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }

        
        //Adds results as textfields in "result_list"
        javax.swing.GroupLayout result_listLayout = new javax.swing.GroupLayout(result_list);
        result_list.removeAll();
        result_list.setLayout(result_listLayout);

        javax.swing.GroupLayout.ParallelGroup hGroup = result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        javax.swing.GroupLayout.SequentialGroup vGroup = result_listLayout.createSequentialGroup();

        for (String s : value) {
            JLabel label = new JLabel(s);

            // Add the label to the horizontal group
            hGroup.addComponent(label);

            // Add the label to the vertical group
            vGroup.addComponent(label);

            // Add some vertical gap between labels (optional)
            vGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED);

        }

        // Set the horizontal and vertical groups for the layout
        result_listLayout.setHorizontalGroup(
                result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(result_listLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(hGroup)
                                .addContainerGap(393, Short.MAX_VALUE))
        );

        result_listLayout.setVerticalGroup(
                result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(result_listLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(vGroup)
                                .addContainerGap(453, Short.MAX_VALUE))
        );

    }//GEN-LAST:event_FBV_buttonActionPerformed

    //ADD/ UPDATE
    private void U_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_buttonActionPerformed
        PropertiesUtil propertiesUtil = new PropertiesUtil();

        try {
            propertiesUtil.init(languages);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        String key = U_textfield.getText();
        String value = U_textfield2.getText();

        JPanel panel;
        panel = U_langs;
        Component[] components = panel.getComponents();

        HashMap<String, String> valueLanguage = new HashMap<>();

        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    String lang = checkBox.getText();
                    valueLanguage.put(lang, value);
                }
            }
        }
        try {
            propertiesUtil.write(key, valueLanguage);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_U_buttonActionPerformed

    //SORT
    private void S_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_buttonActionPerformed
        PropertiesUtil propertiesUtil = new PropertiesUtil();

        try {
            propertiesUtil.init(languages);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            propertiesUtil.sort();
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_S_buttonActionPerformed

    // FIND BY KEY
    private void FBK_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBK_buttonActionPerformed

        PropertiesUtil propertiesUtil = new PropertiesUtil();

        try {
            propertiesUtil.init(languages);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        HashMap<String, String> value = new HashMap();

        try {
            value = propertiesUtil.findValueByKey(FBK_textfield.getText());

            javax.swing.GroupLayout result_listLayout = new javax.swing.GroupLayout(result_list);
            result_list.removeAll();
            result_list.setLayout(result_listLayout);

            javax.swing.GroupLayout.ParallelGroup hGroup = result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
            javax.swing.GroupLayout.SequentialGroup vGroup = result_listLayout.createSequentialGroup();

            for (String i : value.keySet()) {
                String s = String.format("%s: %s", i, value.get(i));

                JLabel label = new JLabel(s);

                // Add the label to the horizontal group
                hGroup.addComponent(label);

                // Add the label to the vertical group
                vGroup.addComponent(label);

                // Add some vertical gap between labels (optional)
                vGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED);
            }

            // Set the horizontal and vertical groups for the layout
            result_listLayout.setHorizontalGroup(
                    result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(result_listLayout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addGroup(hGroup)
                                    .addContainerGap(393, Short.MAX_VALUE))
            );

            result_listLayout.setVerticalGroup(
                    result_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(result_listLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(vGroup)
                                    .addContainerGap(453, Short.MAX_VALUE))
            );

        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FBK_buttonActionPerformed

    //LOAD LANGUAGE BUNDLES
    private void LANG_LOAD_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LANG_LOAD_buttonActionPerformed

        JPanel panel = LANG_panel;
        Component[] components = panel.getComponents();

        for (Component component : components) {
            if (component instanceof JTextField) {

                JTextField input = (JTextField) component;

                String key = input.getName();
                String path = input.getText();

                if (!path.isEmpty()) {
                    languages.put(key, path);
                } else {
                    languages.remove(key);
                }

            }
        }

//        PropertiesUtil propertiesUtil = new PropertiesUtil();
//        
//        try {
//            propertiesUtil.init(languages);
//        } catch (IOException ex) {
//            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_LANG_LOAD_buttonActionPerformed

    /**
     * Adds event listeners to enable a custom paste action for a specific text
     * field.
     */
    private void addEventListeners() {
        // Get the mask for the system-specific shortcut key (e.g., Ctrl or Command key)
        int shortcutMask = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();

        // Get the input map for the text field when it's focused
        InputMap inputMap = PT_textField.getInputMap(JComponent.WHEN_FOCUSED);

        // Get the action map for the text field
        ActionMap actionMap = PT_textField.getActionMap();

        // Define the key combination for the paste action (Ctrl+V)
        KeyStroke pasteKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_V, shortcutMask);

        // Add the key stroke and associated action name to the input map
        inputMap.put(pasteKeyStroke, "paste");

        // Define the action listener for the paste action
        Action actionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                // Get the system clipboard
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();

                // Get the contents of the clipboard
                Transferable transferable = clipboard.getContents(null);

                // Check if the clipboard has data in string format
                if (transferable != null && transferable.isDataFlavorSupported(DataFlavor.stringFlavor)) {
                    try {
                        // Retrieve the content from the clipboard as a string
                        String content = PT_textField.getText() + (String) transferable.getTransferData(DataFlavor.stringFlavor);

                        // Set the content in the text field
                        PT_textField.setText(content);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        };

        // Add the action listener to the action map with the "paste" action name
        actionMap.put("paste", actionListener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_button;
    private javax.swing.JTextField D_textfield;
    private javax.swing.JTextField EN_textField;
    private javax.swing.JTextField ES_textField;
    private javax.swing.JButton FBK_button;
    private javax.swing.JTextField FBK_textfield;
    private javax.swing.JButton FBV_button;
    private javax.swing.JCheckBox FBV_lang_en;
    private javax.swing.JCheckBox FBV_lang_pt;
    private javax.swing.JPanel FBV_langs;
    private javax.swing.JTextField FBV_textfield;
    private javax.swing.JTextField IT_textField;
    private javax.swing.JButton LANG_LOAD_button;
    private javax.swing.JPanel LANG_panel;
    private javax.swing.JTextField PT_textField;
    private javax.swing.JButton S_button;
    private javax.swing.JButton U_button;
    private javax.swing.JCheckBox U_lang_en;
    private javax.swing.JCheckBox U_lang_pt;
    private javax.swing.JPanel U_langs;
    private javax.swing.JTextField U_textfield;
    private javax.swing.JTextField U_textfield2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel result_list;
    // End of variables declaration//GEN-END:variables
}
